/**
 * 成语库扩充脚本
 * 生成完整的成语数据，保持 { word, pinyin, first, last, meaning } 结构
 */

const fs = require('fs');
const path = require('path');

const existingPath = path.join(__dirname, '../src/data/idioms.json');
const existing = JSON.parse(fs.readFileSync(existingPath, 'utf-8'));
const existingWords = new Set(existing.map(e => e.word));

// 大规模成语数据（word, pinyin, first, last, meaning）
// first/last 为首字/末字的无声调拼音
const newIdioms = [
  // === A ===
  { word: "爱不释手", pinyin: "ài bù shì shǒu", first: "ai", last: "shou", meaning: "喜爱到不肯放手。" },
  { word: "爱屋及乌", pinyin: "ài wū jí wū", first: "ai", last: "wu", meaning: "爱一个人连带爱他屋上的乌鸦，比喻爱一个人连带关心跟他有关的人或物。" },
  { word: "安居乐业", pinyin: "ān jū lè yè", first: "an", last: "ye", meaning: "安定地生活，愉快地工作。" },
  { word: "安然无恙", pinyin: "ān rán wú yàng", first: "an", last: "yang", meaning: "平安无事，没有遭受损害或患病。" },
  { word: "暗渡陈仓", pinyin: "àn dù chén cāng", first: "an", last: "cang", meaning: "比喻暗中进行某种活动。" },
  { word: "暗箭伤人", pinyin: "àn jiàn shāng rén", first: "an", last: "ren", meaning: "比喻暗中用阴险手段伤害别人。" },
  { word: "安步当车", pinyin: "ān bù dàng chē", first: "an", last: "che", meaning: "慢慢地步行，就当是坐车。" },
  { word: "安分守己", pinyin: "ān fèn shǒu jǐ", first: "an", last: "ji", meaning: "规矩老实，守本分。" },
  { word: "昂首阔步", pinyin: "áng shǒu kuò bù", first: "ang", last: "bu", meaning: "抬头挺胸地大步走，形容精神振奋。" },
  { word: "按部就班", pinyin: "àn bù jiù bān", first: "an", last: "ban", meaning: "按照一定的条理，遵循一定的程序。" },
  { word: "按图索骥", pinyin: "àn tú suǒ jì", first: "an", last: "ji", meaning: "按照图上画的去找好马，比喻按照线索去寻找。" },
  { word: "黯然失色", pinyin: "àn rán shī sè", first: "an", last: "se", meaning: "指相比之下显得暗淡无光。" },

  // === B ===
  { word: "百发百中", pinyin: "bǎi fā bǎi zhòng", first: "bai", last: "zhong", meaning: "每次都能命中目标，形容射术高明。" },
  { word: "百年大计", pinyin: "bǎi nián dà jì", first: "bai", last: "ji", meaning: "指关系到长远利益的计划或措施。" },
  { word: "百折不挠", pinyin: "bǎi zhé bù náo", first: "bai", last: "nao", meaning: "无论受多少挫折都不退缩，形容意志坚强。" },
  { word: "百闻不如一见", pinyin: "bǎi wén bù rú yī jiàn", first: "bai", last: "jian", meaning: "听别人说多次不如自己亲眼看一次。" },
  { word: "半途而废", pinyin: "bàn tú ér fèi", first: "ban", last: "fei", meaning: "事情做到一半就不做了，不能坚持到底。" },
  { word: "班门弄斧", pinyin: "bān mén nòng fǔ", first: "ban", last: "fu", meaning: "在鲁班门前耍弄斧子，比喻在行家面前卖弄本领。" },
  { word: "包罗万象", pinyin: "bāo luó wàn xiàng", first: "bao", last: "xiang", meaning: "内容丰富，应有尽有。" },
  { word: "抱薪救火", pinyin: "bào xīn jiù huǒ", first: "bao", last: "huo", meaning: "比喻用错误的方法去消除灾祸，反而使灾祸扩大。" },
  { word: "杯弓蛇影", pinyin: "bēi gōng shé yǐng", first: "bei", last: "ying", meaning: "比喻疑神疑鬼，自相惊扰。" },
  { word: "卑躬屈膝", pinyin: "bēi gōng qū xī", first: "bei", last: "xi", meaning: "弯腰下跪，形容没有骨气，巴结奉承。" },
  { word: "背道而驰", pinyin: "bèi dào ér chí", first: "bei", last: "chi", meaning: "朝相反的方向跑去，比喻方向和目的完全相反。" },
  { word: "本末倒置", pinyin: "běn mò dào zhì", first: "ben", last: "zhi", meaning: "把根本的和次要的颠倒了。" },
  { word: "笨鸟先飞", pinyin: "bèn niǎo xiān fēi", first: "ben", last: "fei", meaning: "比喻能力差的人做事先行动，以免落后。" },
  { word: "逼上梁山", pinyin: "bī shàng liáng shān", first: "bi", last: "shan", meaning: "比喻被迫进行反抗或不得不做某事。" },
  { word: "比翼双飞", pinyin: "bǐ yì shuāng fēi", first: "bi", last: "fei", meaning: "比喻夫妻情投意合，在事业上并肩前进。" },
  { word: "毕恭毕敬", pinyin: "bì gōng bì jìng", first: "bi", last: "jing", meaning: "十分恭敬。" },
  { word: "闭月羞花", pinyin: "bì yuè xiū huā", first: "bi", last: "hua", meaning: "形容女子容貌美丽。" },
  { word: "变化无常", pinyin: "biàn huà wú cháng", first: "bian", last: "chang", meaning: "事物经常变化，没有规律。" },
  { word: "变本加厉", pinyin: "biàn běn jiā lì", first: "bian", last: "li", meaning: "变得比原来更加严重。" },
  { word: "标新立异", pinyin: "biāo xīn lì yì", first: "biao", last: "yi", meaning: "提出新奇的主张，表示与众不同。" },
  { word: "别出心裁", pinyin: "bié chū xīn cái", first: "bie", last: "cai", meaning: "独创一格，与众不同。" },
  { word: "别具一格", pinyin: "bié jù yī gé", first: "bie", last: "ge", meaning: "另有一种独特的风格。" },
  { word: "冰天雪地", pinyin: "bīng tiān xuě dì", first: "bing", last: "di", meaning: "形容冰雪漫天盖地，非常寒冷。" },
  { word: "兵不厌诈", pinyin: "bīng bù yàn zhà", first: "bing", last: "zha", meaning: "用兵打仗可以使用欺诈的办法迷惑敌人。" },
  { word: "兵荒马乱", pinyin: "bīng huāng mǎ luàn", first: "bing", last: "luan", meaning: "形容战时社会混乱不安的景象。" },
  { word: "兵临城下", pinyin: "bīng lín chéng xià", first: "bing", last: "xia", meaning: "敌军已来到自己的城墙下面，比喻情势十分危急。" },
  { word: "病入膏肓", pinyin: "bìng rù gāo huāng", first: "bing", last: "huang", meaning: "病已危重到了无法救治的地步。" },
  { word: "博大精深", pinyin: "bó dà jīng shēn", first: "bo", last: "shen", meaning: "形容思想和学识广博高深。" },
  { word: "博古通今", pinyin: "bó gǔ tōng jīn", first: "bo", last: "jin", meaning: "对古代的事知道得很多，并且通晓现代的事情。" },
  { word: "博学多才", pinyin: "bó xué duō cái", first: "bo", last: "cai", meaning: "学识广博，有多方面的才能。" },
  { word: "不耻下问", pinyin: "bù chǐ xià wèn", first: "bu", last: "wen", meaning: "不以向学问比自己差的人请教为耻。" },
  { word: "不寒而栗", pinyin: "bù hán ér lì", first: "bu", last: "li", meaning: "不冷而发抖，形容非常恐惧。" },
  { word: "不假思索", pinyin: "bù jiǎ sī suǒ", first: "bu", last: "suo", meaning: "不经过思考就做出反应。" },
  { word: "不可思议", pinyin: "bù kě sī yì", first: "bu", last: "yi", meaning: "不可想象，不能理解。" },
  { word: "不劳而获", pinyin: "bù láo ér huò", first: "bu", last: "huo", meaning: "不劳动而得到成果。" },
  { word: "不谋而合", pinyin: "bù móu ér hé", first: "bu", last: "he", meaning: "事先没有商量过，意见或行动却完全一致。" },
  { word: "不求甚解", pinyin: "bù qiú shèn jiě", first: "bu", last: "jie", meaning: "只求知道个大概，不求彻底了解。" },
  { word: "不屈不挠", pinyin: "bù qū bù náo", first: "bu", last: "nao", meaning: "比喻在压力面前不屈服，坚强不屈。" },
  { word: "不速之客", pinyin: "bù sù zhī kè", first: "bu", last: "ke", meaning: "没有邀请而自来的客人。" },
  { word: "不约而同", pinyin: "bù yuē ér tóng", first: "bu", last: "tong", meaning: "事先没有约定而相互一致。" },
  { word: "不知所措", pinyin: "bù zhī suǒ cuò", first: "bu", last: "cuo", meaning: "不知道怎么办才好，形容处境为难或心神慌乱。" },
  { word: "不自量力", pinyin: "bù zì liàng lì", first: "bu", last: "li", meaning: "不能正确估计自己的力量。" },
  { word: "步步为营", pinyin: "bù bù wéi yíng", first: "bu", last: "ying", meaning: "军队每前进一步就设下一道营垒，形容行动谨慎。" },

  // === C ===
  { word: "才高八斗", pinyin: "cái gāo bā dǒu", first: "cai", last: "dou", meaning: "形容人的文才高，知识丰富。" },
  { word: "沧海桑田", pinyin: "cāng hǎi sāng tián", first: "cang", last: "tian", meaning: "大海变成农田，比喻世事变化很大。" },
  { word: "沧海一粟", pinyin: "cāng hǎi yī sù", first: "cang", last: "su", meaning: "大海里的一粒粟，比喻非常渺小。" },
  { word: "藏龙卧虎", pinyin: "cáng lóng wò hǔ", first: "cang", last: "hu", meaning: "比喻隐藏着未被发现的人才。" },
  { word: "草木皆兵", pinyin: "cǎo mù jiē bīng", first: "cao", last: "bing", meaning: "把草和树木都当做了敌兵，形容极度恐慌时疑神疑鬼。" },
  { word: "差强人意", pinyin: "chā qiáng rén yì", first: "cha", last: "yi", meaning: "大体上还能使人满意。" },
  { word: "姹紫嫣红", pinyin: "chà zǐ yān hóng", first: "cha", last: "hong", meaning: "形容各种花卉娇艳、美丽。" },
  { word: "长驱直入", pinyin: "cháng qū zhí rù", first: "chang", last: "ru", meaning: "长距离不停地一直往前。" },
  { word: "长年累月", pinyin: "cháng nián lěi yuè", first: "chang", last: "yue", meaning: "形容经历很多年月，很长时间。" },
  { word: "畅所欲言", pinyin: "chàng suǒ yù yán", first: "chang", last: "yan", meaning: "痛痛快快地把心里要说的话都说出来。" },
  { word: "车水马龙", pinyin: "chē shuǐ mǎ lóng", first: "che", last: "long", meaning: "车如流水，马如游龙，形容车马往来不绝。" },
  { word: "沉鱼落雁", pinyin: "chén yú luò yàn", first: "chen", last: "yan", meaning: "形容女子容貌美丽。" },
  { word: "趁火打劫", pinyin: "chèn huǒ dǎ jié", first: "chen", last: "jie", meaning: "趁人家失火时去抢劫，比喻乘人之危谋取私利。" },
  { word: "称心如意", pinyin: "chèn xīn rú yì", first: "chen", last: "yi", meaning: "事与愿符，非常满意。" },
  { word: "承前启后", pinyin: "chéng qián qǐ hòu", first: "cheng", last: "hou", meaning: "继承前人的，开辟今后的。" },
  { word: "诚心诚意", pinyin: "chéng xīn chéng yì", first: "cheng", last: "yi", meaning: "形容十分真挚诚恳。" },
  { word: "乘风破浪", pinyin: "chéng fēng pò làng", first: "cheng", last: "lang", meaning: "比喻志向远大，不怕困难，奋勇前进。" },
  { word: "城门失火殃及池鱼", pinyin: "chéng mén shī huǒ yāng jí chí yú", first: "cheng", last: "yu", meaning: "比喻无辜被连累而遭受损失。" },
  { word: "叱咤风云", pinyin: "chì zhà fēng yún", first: "chi", last: "yun", meaning: "形容声势威力很大。" },
  { word: "赤膊上阵", pinyin: "chì bó shàng zhèn", first: "chi", last: "zhen", meaning: "比喻不顾一切地猛打猛冲。" },
  { word: "冲锋陷阵", pinyin: "chōng fēng xiàn zhèn", first: "chong", last: "zhen", meaning: "向敌人冲锋，深入敌人阵地。" },
  { word: "重蹈覆辙", pinyin: "chóng dǎo fù zhé", first: "chong", last: "zhe", meaning: "再走翻过车的老路，比喻不吸取教训，重犯以前的错误。" },
  { word: "愁眉苦脸", pinyin: "chóu méi kǔ liǎn", first: "chou", last: "lian", meaning: "形容愁苦的神色。" },
  { word: "出尔反尔", pinyin: "chū ěr fǎn ěr", first: "chu", last: "er", meaning: "原指你怎样对人，人就怎样对你。现多指自己说了又反悔。" },
  { word: "出类拔萃", pinyin: "chū lèi bá cuì", first: "chu", last: "cui", meaning: "超出一般，品德、才能出众。" },
  { word: "出口成章", pinyin: "chū kǒu chéng zhāng", first: "chu", last: "zhang", meaning: "话说出来就是一篇文章，形容文思敏捷或口才好。" },
  { word: "出奇制胜", pinyin: "chū qí zhì shèng", first: "chu", last: "sheng", meaning: "用奇兵或奇计战胜敌人。" },
  { word: "出生入死", pinyin: "chū shēng rù sǐ", first: "chu", last: "si", meaning: "形容冒生命危险。" },
  { word: "触目惊心", pinyin: "chù mù jīng xīn", first: "chu", last: "xin", meaning: "看见某种严重情况引起内心的震动。" },
  { word: "川流不息", pinyin: "chuān liú bù xī", first: "chuan", last: "xi", meaning: "像河水流动不停，形容行人、车马等往来不绝。" },
  { word: "穿针引线", pinyin: "chuān zhēn yǐn xiàn", first: "chuan", last: "xian", meaning: "比喻从中联系、牵合。" },
  { word: "唇齿相依", pinyin: "chún chǐ xiāng yī", first: "chun", last: "yi", meaning: "嘴唇和牙齿互相依靠，比喻双方关系密切、相互依存。" },
  { word: "春暖花开", pinyin: "chūn nuǎn huā kāi", first: "chun", last: "kai", meaning: "春天气候温暖，百花盛开。" },
  { word: "春风化雨", pinyin: "chūn fēng huà yǔ", first: "chun", last: "yu", meaning: "比喻良好的教育。" },
  { word: "唇亡齿寒", pinyin: "chún wáng chǐ hán", first: "chun", last: "han", meaning: "嘴唇没了，牙齿就会感到寒冷。比喻利害密切相关。" },
  { word: "从容不迫", pinyin: "cóng róng bù pò", first: "cong", last: "po", meaning: "不慌不忙，非常镇静。" },
  { word: "粗茶淡饭", pinyin: "cū chá dàn fàn", first: "cu", last: "fan", meaning: "形容饮食简单，生活俭朴。" },
  { word: "粗枝大叶", pinyin: "cū zhī dà yè", first: "cu", last: "ye", meaning: "比喻不细致，做事粗心大意。" },
  { word: "寸步难行", pinyin: "cùn bù nán xíng", first: "cun", last: "xing", meaning: "连一步都难以进行，形容走路困难。也比喻处境困难。" },

  // === D ===
  { word: "大材小用", pinyin: "dà cái xiǎo yòng", first: "da", last: "yong", meaning: "把大的材料用于小的用处，比喻使用不当。" },
  { word: "大公无私", pinyin: "dà gōng wú sī", first: "da", last: "si", meaning: "指办事公正，没有私心。" },
  { word: "大海捞针", pinyin: "dà hǎi lāo zhēn", first: "da", last: "zhen", meaning: "从大海里捞一根针，比喻极难找到。" },
  { word: "大惊小怪", pinyin: "dà jīng xiǎo guài", first: "da", last: "guai", meaning: "形容对不足为奇的事情过分惊讶。" },
  { word: "大器晚成", pinyin: "dà qì wǎn chéng", first: "da", last: "cheng", meaning: "指能担当大事的人物要经过长期的锻炼，所以成就比较晚。" },
  { word: "大庭广众", pinyin: "dà tíng guǎng zhòng", first: "da", last: "zhong", meaning: "指聚集很多人的公开场合。" },
  { word: "大同小异", pinyin: "dà tóng xiǎo yì", first: "da", last: "yi", meaning: "大体相同，略有差异。" },
  { word: "大义凛然", pinyin: "dà yì lǐn rán", first: "da", last: "ran", meaning: "由于胸怀正义而神态庄严，令人敬畏。" },
  { word: "大智若愚", pinyin: "dà zhì ruò yú", first: "da", last: "yu", meaning: "才智很高而不露锋芒，表面上看好像愚笨。" },
  { word: "呆若木鸡", pinyin: "dāi ruò mù jī", first: "dai", last: "ji", meaning: "呆得像木头鸡一样，形容因恐惧或惊讶而发愣的样子。" },
  { word: "当机立断", pinyin: "dāng jī lì duàn", first: "dang", last: "duan", meaning: "在紧要时刻立即做出决断。" },
  { word: "当仁不让", pinyin: "dāng rén bù ràng", first: "dang", last: "rang", meaning: "遇到应该做的事就积极主动去做，不推让。" },
  { word: "道听途说", pinyin: "dào tīng tú shuō", first: "dao", last: "shuo", meaning: "路上听来的又在路上传播的话，指没有根据的传闻。" },
  { word: "得不偿失", pinyin: "dé bù cháng shī", first: "de", last: "shi", meaning: "所得的利益抵不上所受的损失。" },
  { word: "得过且过", pinyin: "dé guò qiě guò", first: "de", last: "guo", meaning: "只要能够过得去就这样过下去，形容胸无大志。" },
  { word: "得寸进尺", pinyin: "dé cùn jìn chǐ", first: "de", last: "chi", meaning: "得到一寸又想进一尺，比喻贪心不满足。" },
  { word: "得心应手", pinyin: "dé xīn yìng shǒu", first: "de", last: "shou", meaning: "心里怎么想，手就能怎么做，形容运用自如。" },
  { word: "德高望重", pinyin: "dé gāo wàng zhòng", first: "de", last: "zhong", meaning: "品德高尚，声望很高。" },
  { word: "灯红酒绿", pinyin: "dēng hóng jiǔ lǜ", first: "deng", last: "lv", meaning: "形容奢侈淫逸的生活。" },
  { word: "低三下四", pinyin: "dī sān xià sì", first: "di", last: "si", meaning: "形容态度卑贱低下。" },
  { word: "颠倒黑白", pinyin: "diān dǎo hēi bái", first: "dian", last: "bai", meaning: "把黑的说成白的，把白的说成黑的。比喻故意歪曲事实。" },
  { word: "雕虫小技", pinyin: "diāo chóng xiǎo jì", first: "diao", last: "ji", meaning: "比喻微不足道的技能。" },
  { word: "调虎离山", pinyin: "diào hǔ lí shān", first: "diao", last: "shan", meaning: "设法使老虎离开原来的山冈，比喻用计使对方离开有利的地位。" },
  { word: "顶天立地", pinyin: "dǐng tiān lì dì", first: "ding", last: "di", meaning: "形容形象高大，气概雄伟豪迈。" },
  { word: "东山再起", pinyin: "dōng shān zài qǐ", first: "dong", last: "qi", meaning: "指退隐后再度出任要职，也比喻失势之后又重新得势。" },
  { word: "东施效颦", pinyin: "dōng shī xiào pín", first: "dong", last: "pin", meaning: "比喻不顾条件生搬硬套，效果适得其反。" },
  { word: "东张西望", pinyin: "dōng zhāng xī wàng", first: "dong", last: "wang", meaning: "向四处张望。" },
  { word: "独当一面", pinyin: "dú dāng yī miàn", first: "du", last: "mian", meaning: "单独负责一个方面的工作。" },
  { word: "独一无二", pinyin: "dú yī wú èr", first: "du", last: "er", meaning: "没有相同的，没有可以相比的。" },
  { word: "对牛弹琴", pinyin: "duì niú tán qín", first: "dui", last: "qin", meaning: "比喻对不懂道理的人讲道理。" },
  { word: "多此一举", pinyin: "duō cǐ yī jǔ", first: "duo", last: "ju", meaning: "做了多余的事，反而不恰当。" },

  // === E ===
  { word: "耳濡目染", pinyin: "ěr rú mù rǎn", first: "er", last: "ran", meaning: "耳朵经常听到，眼睛经常看到，不知不觉地受到影响。" },
  { word: "耳目一新", pinyin: "ěr mù yī xīn", first: "er", last: "xin", meaning: "听到的、看到的跟以前不同，使人感到新鲜。" },
  { word: "尔虞我诈", pinyin: "ěr yú wǒ zhà", first: "er", last: "zha", meaning: "比喻互相欺骗。" },

  // === F ===
  { word: "发愤图强", pinyin: "fā fèn tú qiáng", first: "fa", last: "qiang", meaning: "下定决心，努力谋求强盛。" },
  { word: "翻天覆地", pinyin: "fān tiān fù dì", first: "fan", last: "di", meaning: "形容变化巨大而彻底。" },
  { word: "防患未然", pinyin: "fáng huàn wèi rán", first: "fang", last: "ran", meaning: "在事故或灾害尚未发生之前就采取预防措施。" },
  { word: "飞黄腾达", pinyin: "fēi huáng téng dá", first: "fei", last: "da", meaning: "比喻骤然得志，官职升得很快。" },
  { word: "肺腑之言", pinyin: "fèi fǔ zhī yán", first: "fei", last: "yan", meaning: "发自内心的真诚的话。" },
  { word: "奋不顾身", pinyin: "fèn bù gù shēn", first: "fen", last: "shen", meaning: "奋勇向前，不考虑个人安危。" },
  { word: "丰功伟绩", pinyin: "fēng gōng wěi jì", first: "feng", last: "ji", meaning: "伟大的功绩。" },
  { word: "风餐露宿", pinyin: "fēng cān lù sù", first: "feng", last: "su", meaning: "在大风里吃饭，在露天睡觉，形容旅途生活的辛苦。" },
  { word: "风驰电掣", pinyin: "fēng chí diàn chè", first: "feng", last: "che", meaning: "形容非常迅速，像风吹电闪一样。" },
  { word: "风吹草动", pinyin: "fēng chuī cǎo dòng", first: "feng", last: "dong", meaning: "比喻轻微的动荡或变故。" },
  { word: "风花雪月", pinyin: "fēng huā xuě yuè", first: "feng", last: "yue", meaning: "原指古典文学作品里描写自然景物的四种对象，后借指堆砌辞藻而内容空泛的诗文。" },
  { word: "风平浪静", pinyin: "fēng píng làng jìng", first: "feng", last: "jing", meaning: "没有风浪，比喻平静无事。" },
  { word: "风雨同舟", pinyin: "fēng yǔ tóng zhōu", first: "feng", last: "zhou", meaning: "在狂风暴雨中同乘一条船，比喻共同经历患难。" },
  { word: "风雨无阻", pinyin: "fēng yǔ wú zǔ", first: "feng", last: "zu", meaning: "刮风下雨也不阻挡，表示无论什么情况都照常进行。" },
  { word: "釜底抽薪", pinyin: "fǔ dǐ chōu xīn", first: "fu", last: "xin", meaning: "把锅底下的柴火抽走，比喻从根本上解决问题。" },
  { word: "赴汤蹈火", pinyin: "fù tāng dǎo huǒ", first: "fu", last: "huo", meaning: "比喻不避艰险，奋勇向前。" },
  { word: "负荆请罪", pinyin: "fù jīng qǐng zuì", first: "fu", last: "zui", meaning: "表示向人认错赔罪。" },
  { word: "覆水难收", pinyin: "fù shuǐ nán shōu", first: "fu", last: "shou", meaning: "泼出去的水不能再收回来。比喻事情已成定局，无法挽回。" },

  // === G ===
  { word: "刚愎自用", pinyin: "gāng bì zì yòng", first: "gang", last: "yong", meaning: "十分固执自信，不考虑别人的意见。" },
  { word: "高枕无忧", pinyin: "gāo zhěn wú yōu", first: "gao", last: "you", meaning: "垫高枕头安心地睡觉，比喻平安无事，不必担忧。" },
  { word: "高瞻远瞩", pinyin: "gāo zhān yuǎn zhǔ", first: "gao", last: "zhu", meaning: "站得高，看得远，比喻眼光远大。" },
  { word: "各抒己见", pinyin: "gè shū jǐ jiàn", first: "ge", last: "jian", meaning: "各人充分发表自己的意见。" },
  { word: "根深蒂固", pinyin: "gēn shēn dì gù", first: "gen", last: "gu", meaning: "根扎得深，蒂长得牢。比喻基础牢固，不可动摇。" },
  { word: "功亏一篑", pinyin: "gōng kuī yī kuì", first: "gong", last: "kui", meaning: "比喻做事情只差最后一步，却因此而失败。" },
  { word: "功德无量", pinyin: "gōng dé wú liàng", first: "gong", last: "liang", meaning: "功劳恩德无法估量。" },
  { word: "攻其不备", pinyin: "gōng qí bù bèi", first: "gong", last: "bei", meaning: "趁敌人没有防备的时候进攻。" },
  { word: "狗急跳墙", pinyin: "gǒu jí tiào qiáng", first: "gou", last: "qiang", meaning: "比喻走投无路时采取不顾一切的行动。" },
  { word: "孤注一掷", pinyin: "gū zhù yī zhì", first: "gu", last: "zhi", meaning: "把所有的钱一次押上去赌，比喻在危急时用尽所有力量做最后一次冒险。" },
  { word: "古色古香", pinyin: "gǔ sè gǔ xiāng", first: "gu", last: "xiang", meaning: "形容字画、陈设等具有古雅的色彩和情调。" },
  { word: "顾名思义", pinyin: "gù míng sī yì", first: "gu", last: "yi", meaning: "看到名称就联想到它的含义。" },
  { word: "光明磊落", pinyin: "guāng míng lěi luò", first: "guang", last: "luo", meaning: "形容心地坦白，言行正派。" },
  { word: "光怪陆离", pinyin: "guāng guài lù lí", first: "guang", last: "li", meaning: "形容奇形怪状、五颜六色。" },
  { word: "鬼斧神工", pinyin: "guǐ fǔ shén gōng", first: "gui", last: "gong", meaning: "形容建筑、雕塑等技艺的精巧。" },
  { word: "过河拆桥", pinyin: "guò hé chāi qiáo", first: "guo", last: "qiao", meaning: "比喻达到目的后就把帮过自己忙的人一脚踢开。" },
  { word: "过目不忘", pinyin: "guò mù bù wàng", first: "guo", last: "wang", meaning: "看过一遍就不忘记，形容记忆力非常强。" },

  // === H ===
  { word: "含辛茹苦", pinyin: "hán xīn rú kǔ", first: "han", last: "ku", meaning: "经受艰辛困苦。" },
  { word: "含沙射影", pinyin: "hán shā shè yǐng", first: "han", last: "ying", meaning: "比喻暗中诽谤中伤。" },
  { word: "汗流浃背", pinyin: "hàn liú jiā bèi", first: "han", last: "bei", meaning: "形容非常恐惧或非常害怕。" },
  { word: "好高骛远", pinyin: "hào gāo wù yuǎn", first: "hao", last: "yuan", meaning: "不切实际地追求过高过远的目标。" },
  { word: "浩浩荡荡", pinyin: "hào hào dàng dàng", first: "hao", last: "dang", meaning: "形容水势广大的样子或形容声势壮阔。" },
  { word: "和颜悦色", pinyin: "hé yán yuè sè", first: "he", last: "se", meaning: "脸色和蔼喜悦。" },
  { word: "鹤立鸡群", pinyin: "hè lì jī qún", first: "he", last: "qun", meaning: "比喻一个人的才能或仪表在一群人里头显得很突出。" },
  { word: "横行霸道", pinyin: "héng xíng bà dào", first: "heng", last: "dao", meaning: "横行：不讲道理；霸道：蛮不讲理。形容蛮横无理。" },
  { word: "厚积薄发", pinyin: "hòu jī bó fā", first: "hou", last: "fa", meaning: "多多积蓄，慢慢放出。形容准备充分。" },
  { word: "后来居上", pinyin: "hòu lái jū shàng", first: "hou", last: "shang", meaning: "后来的超过先前的。" },
  { word: "后生可畏", pinyin: "hòu shēng kě wèi", first: "hou", last: "wei", meaning: "年轻人是可敬畏的。" },
  { word: "狐假虎威", pinyin: "hú jiǎ hǔ wēi", first: "hu", last: "wei", meaning: "比喻仗着别人的势力欺压人。" },
  { word: "虎头蛇尾", pinyin: "hǔ tóu shé wěi", first: "hu", last: "wei", meaning: "比喻做事有始无终。" },
  { word: "花好月圆", pinyin: "huā hǎo yuè yuán", first: "hua", last: "yuan", meaning: "比喻美好圆满。" },
  { word: "花言巧语", pinyin: "huā yán qiǎo yǔ", first: "hua", last: "yu", meaning: "好听而不实际的话。" },
  { word: "画龙点睛", pinyin: "huà lóng diǎn jīng", first: "hua", last: "jing", meaning: "比喻在关键的地方加上精辟的语句，使内容更加生动传神。" },
  { word: "画蛇添足", pinyin: "huà shé tiān zú", first: "hua", last: "zu", meaning: "做多余的事，反而不恰当。" },
  { word: "欢天喜地", pinyin: "huān tiān xǐ dì", first: "huan", last: "di", meaning: "形容非常高兴。" },
  { word: "患难与共", pinyin: "huàn nàn yǔ gòng", first: "huan", last: "gong", meaning: "同心协力，共同承担困难或险境。" },
  { word: "焕然一新", pinyin: "huàn rán yī xīn", first: "huan", last: "xin", meaning: "面貌焕然改变，显出崭新的面貌。" },
  { word: "荒无人烟", pinyin: "huāng wú rén yān", first: "huang", last: "yan", meaning: "十分荒凉，没有人家。" },
  { word: "恍然大悟", pinyin: "huǎng rán dà wù", first: "huang", last: "wu", meaning: "形容一下子明白过来。" },
  { word: "挥金如土", pinyin: "huī jīn rú tǔ", first: "hui", last: "tu", meaning: "挥霍钱财如同泥土一样，形容极端浪费。" },
  { word: "回味无穷", pinyin: "huí wèi wú qióng", first: "hui", last: "qiong", meaning: "比喻回想某一事物，越想越觉得有意思。" },
  { word: "浑水摸鱼", pinyin: "hún shuǐ mō yú", first: "hun", last: "yu", meaning: "比喻乘混乱的时候从中捞取利益。" },
  { word: "火上浇油", pinyin: "huǒ shàng jiāo yóu", first: "huo", last: "you", meaning: "比喻使人更加愤怒或使情况更加严重。" },
  { word: "祸不单行", pinyin: "huò bù dān xíng", first: "huo", last: "xing", meaning: "不幸的事接二连三地发生。" },

  // === J ===
  { word: "机不可失", pinyin: "jī bù kě shī", first: "ji", last: "shi", meaning: "好的时机不可放过。" },
  { word: "鸡飞蛋打", pinyin: "jī fēi dàn dǎ", first: "ji", last: "da", meaning: "比喻两头落空，什么也没有得到。" },
  { word: "鸡犬不宁", pinyin: "jī quǎn bù níng", first: "ji", last: "ning", meaning: "形容骚扰得厉害，连鸡犬都不得安宁。" },
  { word: "集思广益", pinyin: "jí sī guǎng yì", first: "ji", last: "yi", meaning: "集中群众的智慧，广泛吸收有益的意见。" },
  { word: "急中生智", pinyin: "jí zhōng shēng zhì", first: "ji", last: "zhi", meaning: "在紧急中想出好办法。" },
  { word: "坚持不懈", pinyin: "jiān chí bù xiè", first: "jian", last: "xie", meaning: "坚持到底，一点不松懈。" },
  { word: "坚定不移", pinyin: "jiān dìng bù yí", first: "jian", last: "yi", meaning: "稳定坚强，毫不动摇。" },
  { word: "见多识广", pinyin: "jiàn duō shí guǎng", first: "jian", last: "guang", meaning: "见过的多，知道的广，形容阅历深、经验多。" },
  { word: "见缝插针", pinyin: "jiàn fèng chā zhēn", first: "jian", last: "zhen", meaning: "比喻尽可能利用一切可以利用的空间或时间。" },
  { word: "见利忘义", pinyin: "jiàn lì wàng yì", first: "jian", last: "yi", meaning: "看到有利可图就忘了道义。" },
  { word: "见异思迁", pinyin: "jiàn yì sī qiān", first: "jian", last: "qian", meaning: "看见别的事物就想改变原来的主意。" },
  { word: "艰苦卓绝", pinyin: "jiān kǔ zhuó jué", first: "jian", last: "jue", meaning: "形容十分艰苦，超出了寻常。" },
  { word: "锦上添花", pinyin: "jǐn shàng tiān huā", first: "jin", last: "hua", meaning: "比喻好上加好。" },
  { word: "锦囊妙计", pinyin: "jǐn náng miào jì", first: "jin", last: "ji", meaning: "比喻能解决紧急问题的好办法。" },
  { word: "金蝉脱壳", pinyin: "jīn chán tuō qiào", first: "jin", last: "qiao", meaning: "比喻用计脱身，使人不能及时发觉。" },
  { word: "精益求精", pinyin: "jīng yì qiú jīng", first: "jing", last: "jing", meaning: "已经很好了，还要求更好。" },
  { word: "精兵简政", pinyin: "jīng bīng jiǎn zhèng", first: "jing", last: "zheng", meaning: "缩小机构，精简人员。" },
  { word: "惊弓之鸟", pinyin: "jīng gōng zhī niǎo", first: "jing", last: "niao", meaning: "比喻受过惊吓的人碰到一点动静就非常害怕。" },
  { word: "惊天动地", pinyin: "jīng tiān dòng dì", first: "jing", last: "di", meaning: "形容声音特别响亮或事业伟大。" },
  { word: "精打细算", pinyin: "jīng dǎ xì suàn", first: "jing", last: "suan", meaning: "细密地计算，形容在使用人力物力上计划得很精密。" },
  { word: "井然有序", pinyin: "jǐng rán yǒu xù", first: "jing", last: "xu", meaning: "形容做事有条理。" },
  { word: "井底之蛙", pinyin: "jǐng dǐ zhī wā", first: "jing", last: "wa", meaning: "比喻见识短浅的人。" },
  { word: "九牛一毛", pinyin: "jiǔ niú yī máo", first: "jiu", last: "mao", meaning: "好像九头牛身上的一根毛，比喻极大数量中微不足道的数量。" },
  { word: "九死一生", pinyin: "jiǔ sǐ yī shēng", first: "jiu", last: "sheng", meaning: "形容经历很大危险而幸存。" },
  { word: "居安思危", pinyin: "jū ān sī wēi", first: "ju", last: "wei", meaning: "处在安乐的环境中要想到可能会出现的困难和危险。" },
  { word: "举一反三", pinyin: "jǔ yī fǎn sān", first: "ju", last: "san", meaning: "从一件事情类推而知道其他许多事情。" },
  { word: "举世闻名", pinyin: "jǔ shì wén míng", first: "ju", last: "ming", meaning: "全世界都知道，形容名望极大。" },
  { word: "举世瞩目", pinyin: "jǔ shì zhǔ mù", first: "ju", last: "mu", meaning: "全世界的人都注视着。" },
  { word: "举棋不定", pinyin: "jǔ qí bù dìng", first: "ju", last: "ding", meaning: "拿着棋子不知道该怎么下，比喻犹豫不决。" },
  { word: "聚精会神", pinyin: "jù jīng huì shén", first: "ju", last: "shen", meaning: "集中精神，注意力高度集中。" },

  // === K ===
  { word: "开诚布公", pinyin: "kāi chéng bù gōng", first: "kai", last: "gong", meaning: "指以诚心待人，坦白无私。" },
  { word: "开门见山", pinyin: "kāi mén jiàn shān", first: "kai", last: "shan", meaning: "比喻说话写文章直截了当。" },
  { word: "开天辟地", pinyin: "kāi tiān pì dì", first: "kai", last: "di", meaning: "比喻前所未有的伟大事业。" },
  { word: "刻不容缓", pinyin: "kè bù róng huǎn", first: "ke", last: "huan", meaning: "指形势紧迫，一刻也不允许拖延。" },
  { word: "刻舟求剑", pinyin: "kè zhōu qiú jiàn", first: "ke", last: "jian", meaning: "比喻拘泥成例，不知道跟着情势的变化而改变看法或办法。" },
  { word: "口是心非", pinyin: "kǒu shì xīn fēi", first: "kou", last: "fei", meaning: "嘴里说的是一套，心里想的又是一套。" },
  { word: "口若悬河", pinyin: "kǒu ruò xuán hé", first: "kou", last: "he", meaning: "形容能说会辩，说起话来滔滔不绝。" },
  { word: "苦口婆心", pinyin: "kǔ kǒu pó xīn", first: "ku", last: "xin", meaning: "比喻善意而又耐心地劝导。" },
  { word: "夸夸其谈", pinyin: "kuā kuā qí tán", first: "kua", last: "tan", meaning: "形容说话、写文章浮夸不切实际。" },
  { word: "快马加鞭", pinyin: "kuài mǎ jiā biān", first: "kuai", last: "bian", meaning: "比喻快上加快。" },
  { word: "旷日持久", pinyin: "kuàng rì chí jiǔ", first: "kuang", last: "jiu", meaning: "荒废时间，拖得很久。" },

  // === L ===
  { word: "来龙去脉", pinyin: "lái lóng qù mài", first: "lai", last: "mai", meaning: "比喻人、物的来历或事情的前因后果。" },
  { word: "滥竽充数", pinyin: "làn yú chōng shù", first: "lan", last: "shu", meaning: "比喻没有本领的人冒充有本领。" },
  { word: "老马识途", pinyin: "lǎo mǎ shí tú", first: "lao", last: "tu", meaning: "比喻有经验的人对事情比较熟悉。" },
  { word: "老生常谈", pinyin: "lǎo shēng cháng tán", first: "lao", last: "tan", meaning: "老书生经常说的话，比喻人们听惯了的没有新鲜意思的话。" },
  { word: "老当益壮", pinyin: "lǎo dāng yì zhuàng", first: "lao", last: "zhuang", meaning: "年纪虽老而志气更旺盛。" },
  { word: "乐不思蜀", pinyin: "lè bù sī shǔ", first: "le", last: "shu", meaning: "比喻乐而忘本或乐而忘返。" },
  { word: "乐善好施", pinyin: "lè shàn hào shī", first: "le", last: "shi", meaning: "喜欢做善事，乐于拿财物接济有困难的人。" },
  { word: "理直气壮", pinyin: "lǐ zhí qì zhuàng", first: "li", last: "zhuang", meaning: "道理充分，说话有气势。" },
  { word: "力不从心", pinyin: "lì bù cóng xīn", first: "li", last: "xin", meaning: "心里想做某事，但力量不够。" },
  { word: "历历在目", pinyin: "lì lì zài mù", first: "li", last: "mu", meaning: "指远方的景物看得清清楚楚。" },
  { word: "临危不惧", pinyin: "lín wēi bù jù", first: "lin", last: "ju", meaning: "面临着危险从容不迫，毫不畏惧。" },
  { word: "临渊羡鱼", pinyin: "lín yuān xiàn yú", first: "lin", last: "yu", meaning: "比喻只有愿望而没有措施。" },
  { word: "龙飞凤舞", pinyin: "lóng fēi fèng wǔ", first: "long", last: "wu", meaning: "形容书法笔势有力，灵活舒展。" },
  { word: "龙争虎斗", pinyin: "lóng zhēng hǔ dòu", first: "long", last: "dou", meaning: "形容斗争或竞赛很激烈。" },
  { word: "碌碌无为", pinyin: "lù lù wú wéi", first: "lu", last: "wei", meaning: "平平庸庸，无所作为。" },
  { word: "路遥知马力", pinyin: "lù yáo zhī mǎ lì", first: "lu", last: "li", meaning: "路途遥远才能知道马的力气大小。比喻经过长期的考验才能看出人心的好坏。" },
  { word: "落井下石", pinyin: "luò jǐng xià shí", first: "luo", last: "shi", meaning: "比喻乘人有危难时加以陷害。" },

  // === M ===
  { word: "马到成功", pinyin: "mǎ dào chéng gōng", first: "ma", last: "gong", meaning: "形容工作刚开始就取得成功。" },
  { word: "马不停蹄", pinyin: "mǎ bù tíng tí", first: "ma", last: "ti", meaning: "比喻不停顿地向前走。" },
  { word: "满面春风", pinyin: "mǎn miàn chūn fēng", first: "man", last: "feng", meaning: "形容满脸笑容。" },
  { word: "盲人摸象", pinyin: "máng rén mō xiàng", first: "mang", last: "xiang", meaning: "比喻只知道事物的一部分就妄下结论。" },
  { word: "茅塞顿开", pinyin: "máo sè dùn kāi", first: "mao", last: "kai", meaning: "原来心里好像有茅草堵塞着，现在忽然被打开了。形容突然理解了。" },
  { word: "眉飞色舞", pinyin: "méi fēi sè wǔ", first: "mei", last: "wu", meaning: "形容非常高兴或得意。" },
  { word: "美中不足", pinyin: "měi zhōng bù zú", first: "mei", last: "zu", meaning: "虽然很好，但还有缺陷。" },
  { word: "门庭若市", pinyin: "mén tíng ruò shì", first: "men", last: "shi", meaning: "门前和院子里热闹得像市场一样，形容来的人很多。" },
  { word: "名副其实", pinyin: "míng fù qí shí", first: "ming", last: "shi", meaning: "名称或名声与实际相符合。" },
  { word: "名列前茅", pinyin: "míng liè qián máo", first: "ming", last: "mao", meaning: "比喻名次列在前面。" },
  { word: "名落孙山", pinyin: "míng luò sūn shān", first: "ming", last: "shan", meaning: "比喻考试或选拔没有录取。" },
  { word: "明察秋毫", pinyin: "míng chá qiū háo", first: "ming", last: "hao", meaning: "目光敏锐，可以看清极其细小的东西。形容人能洞察事理。" },
  { word: "明珠暗投", pinyin: "míng zhū àn tóu", first: "ming", last: "tou", meaning: "比喻怀才不遇。" },
  { word: "摩拳擦掌", pinyin: "mó quán cā zhǎng", first: "mo", last: "zhang", meaning: "形容战斗或劳动之前，人们精神振奋、跃跃欲试的样子。" },
  { word: "墨守成规", pinyin: "mò shǒu chéng guī", first: "mo", last: "gui", meaning: "比喻因循守旧，不肯改进。" },
  { word: "目不暇接", pinyin: "mù bù xiá jiē", first: "mu", last: "jie", meaning: "眼睛来不及看，形容东西多得看不过来。" },
  { word: "目瞪口呆", pinyin: "mù dèng kǒu dāi", first: "mu", last: "dai", meaning: "形容吃惊而发愣的样子。" },
  { word: "目中无人", pinyin: "mù zhōng wú rén", first: "mu", last: "ren", meaning: "眼中没有别人，形容骄傲自大。" },

  // === N ===
  { word: "南辕北辙", pinyin: "nán yuán běi zhé", first: "nan", last: "zhe", meaning: "想向南却向北走，比喻行动和目的相反。" },
  { word: "难以置信", pinyin: "nán yǐ zhì xìn", first: "nan", last: "xin", meaning: "事情的出人意料，让人难以相信。" },
  { word: "能工巧匠", pinyin: "néng gōng qiǎo jiàng", first: "neng", last: "jiang", meaning: "技艺高超的工匠。" },
  { word: "弄巧成拙", pinyin: "nòng qiǎo chéng zhuō", first: "nong", last: "zhuo", meaning: "想耍巧妙的手段，结果反而坏了事。" },

  // === P ===
  { word: "排山倒海", pinyin: "pái shān dǎo hǎi", first: "pai", last: "hai", meaning: "推开高山，翻倒大海。形容力量强盛，声势浩大。" },
  { word: "旁若无人", pinyin: "páng ruò wú rén", first: "pang", last: "ren", meaning: "好像旁边没有人，形容态度自然或高傲。" },
  { word: "抛砖引玉", pinyin: "pāo zhuān yǐn yù", first: "pao", last: "yu", meaning: "抛出砖去引回玉来，比喻用自己不成熟的意见引出别人更好的意见。" },
  { word: "赔了夫人又折兵", pinyin: "péi le fū rén yòu zhé bīng", first: "pei", last: "bing", meaning: "比喻想占便宜反而受了双重损失。" },
  { word: "蓬荜生辉", pinyin: "péng bì shēng huī", first: "peng", last: "hui", meaning: "使简陋的房屋增添光辉，多用于谦辞。" },
  { word: "披荆斩棘", pinyin: "pī jīng zhǎn jí", first: "pi", last: "ji", meaning: "比喻在前进道路上清除障碍，克服困难。" },
  { word: "评头论足", pinyin: "píng tóu lùn zú", first: "ping", last: "zu", meaning: "对人对事多方挑剔。" },
  { word: "破釜沉舟", pinyin: "pò fǔ chén zhōu", first: "po", last: "zhou", meaning: "比喻下决心不顾一切地干到底。" },
  { word: "迫不及待", pinyin: "pò bù jí dài", first: "po", last: "dai", meaning: "急迫得不能等待。" },
  { word: "朴实无华", pinyin: "pǔ shí wú huá", first: "pu", last: "hua", meaning: "质朴实在而不浮华。" },

  // === Q ===
  { word: "奇花异草", pinyin: "qí huā yì cǎo", first: "qi", last: "cao", meaning: "原指稀奇少见的花草，后也形容奇巧的事物。" },
  { word: "奇珍异宝", pinyin: "qí zhēn yì bǎo", first: "qi", last: "bao", meaning: "珍异难得的宝物。" },
  { word: "旗开得胜", pinyin: "qí kāi dé shèng", first: "qi", last: "sheng", meaning: "刚一打开旗帜就取得了胜利，比喻一举成功。" },
  { word: "千方百计", pinyin: "qiān fāng bǎi jì", first: "qian", last: "ji", meaning: "想尽一切办法。" },
  { word: "千里迢迢", pinyin: "qiān lǐ tiáo tiáo", first: "qian", last: "tiao", meaning: "形容路途遥远。" },
  { word: "千钧一发", pinyin: "qiān jūn yī fà", first: "qian", last: "fa", meaning: "比喻情况万分危急。" },
  { word: "千篇一律", pinyin: "qiān piān yī lǜ", first: "qian", last: "lv", meaning: "形式或内容千篇一样。" },
  { word: "千载难逢", pinyin: "qiān zǎi nán féng", first: "qian", last: "feng", meaning: "一千年也难碰到一次，形容机会极其难得。" },
  { word: "前车之鉴", pinyin: "qián chē zhī jiàn", first: "qian", last: "jian", meaning: "前面车子翻倒的教训，比喻先前的失败可以作为以后的教训。" },
  { word: "前赴后继", pinyin: "qián fù hòu jì", first: "qian", last: "ji", meaning: "前面的冲上去了，后面的紧跟上来。" },
  { word: "前功尽弃", pinyin: "qián gōng jìn qì", first: "qian", last: "qi", meaning: "以前的功劳全部丢失。" },
  { word: "浅尝辄止", pinyin: "qiǎn cháng zhé zhǐ", first: "qian", last: "zhi", meaning: "略微尝试一下就停下来，比喻不肯下功夫深入钻研。" },
  { word: "巧妙绝伦", pinyin: "qiǎo miào jué lún", first: "qiao", last: "lun", meaning: "灵巧高明，超乎寻常。" },
  { word: "切磋琢磨", pinyin: "qiē cuō zhuó mó", first: "qie", last: "mo", meaning: "将骨角玉石加工制成器物，比喻学习或研究问题时互相讨论。" },
  { word: "勤学苦练", pinyin: "qín xué kǔ liàn", first: "qin", last: "lian", meaning: "认真学习，刻苦训练。" },
  { word: "青出于蓝", pinyin: "qīng chū yú lán", first: "qing", last: "lan", meaning: "比喻学生超过老师或后人胜过前人。" },
  { word: "轻描淡写", pinyin: "qīng miáo dàn xiě", first: "qing", last: "xie", meaning: "形容说话或写文章把重要问题轻轻带过。" },
  { word: "情不自禁", pinyin: "qíng bù zì jīn", first: "qing", last: "jin", meaning: "抑制不住自己的感情。" },
  { word: "全力以赴", pinyin: "quán lì yǐ fù", first: "quan", last: "fu", meaning: "把全部力量都投入进去。" },
  { word: "全心全意", pinyin: "quán xīn quán yì", first: "quan", last: "yi", meaning: "投入全部精力，毫无保留。" },
  { word: "拳打脚踢", pinyin: "quán dǎ jiǎo tī", first: "quan", last: "ti", meaning: "用拳打，用脚踢。形容痛打。" },

  // === R ===
  { word: "热火朝天", pinyin: "rè huǒ cháo tiān", first: "re", last: "tian", meaning: "形容群众性的活动情绪热烈。" },
  { word: "任劳任怨", pinyin: "rèn láo rèn yuàn", first: "ren", last: "yuan", meaning: "做事不辞劳苦，不怕别人埋怨。" },
  { word: "任重道远", pinyin: "rèn zhòng dào yuǎn", first: "ren", last: "yuan", meaning: "担子很重，路程很远。比喻责任重大而艰巨。" },
  { word: "日积月累", pinyin: "rì jī yuè lěi", first: "ri", last: "lei", meaning: "一天一天地、一月一月地不断积累。" },
  { word: "日新月异", pinyin: "rì xīn yuè yì", first: "ri", last: "yi", meaning: "每天每月都有新的变化。形容发展、进步很快。" },
  { word: "入木三分", pinyin: "rù mù sān fēn", first: "ru", last: "fen", meaning: "形容书法有力，也比喻议论深刻。" },
  { word: "如火如荼", pinyin: "rú huǒ rú tú", first: "ru", last: "tu", meaning: "像火那样红，像荼那样白。形容旺盛热烈。" },
  { word: "如虎添翼", pinyin: "rú hǔ tiān yì", first: "ru", last: "yi", meaning: "好像老虎长上了翅膀。比喻强有力的人得到帮助变得更加强有力。" },
  { word: "如鱼得水", pinyin: "rú yú dé shuǐ", first: "ru", last: "shui", meaning: "好像鱼得到水一样。比喻得到跟自己十分投合的人或对自己很合适的环境。" },

  // === S ===
  { word: "三番五次", pinyin: "sān fān wǔ cì", first: "san", last: "ci", meaning: "形容屡次，多次。" },
  { word: "三思而行", pinyin: "sān sī ér xíng", first: "san", last: "xing", meaning: "反复考虑后再做，不要鲁莽行事。" },
  { word: "三心二意", pinyin: "sān xīn èr yì", first: "san", last: "yi", meaning: "犹豫不决，意志不坚定。" },
  { word: "丧家之犬", pinyin: "sàng jiā zhī quǎn", first: "sang", last: "quan", meaning: "比喻失去靠山、到处乱跑的人。" },
  { word: "杀鸡儆猴", pinyin: "shā jī jǐng hóu", first: "sha", last: "hou", meaning: "杀鸡给猴子看，比喻用惩罚一个人的办法来警告别的人。" },
  { word: "山穷水尽", pinyin: "shān qióng shuǐ jìn", first: "shan", last: "jin", meaning: "山和水都到了尽头，比喻陷入绝境。" },
  { word: "山清水秀", pinyin: "shān qīng shuǐ xiù", first: "shan", last: "xiu", meaning: "形容风景优美。" },
  { word: "赏心悦目", pinyin: "shǎng xīn yuè mù", first: "shang", last: "mu", meaning: "因看到美好的事物而心情舒畅。" },
  { word: "上行下效", pinyin: "shàng xíng xià xiào", first: "shang", last: "xiao", meaning: "上面的人怎么做，下面的人就跟着怎么做。" },
  { word: "少见多怪", pinyin: "shǎo jiàn duō guài", first: "shao", last: "guai", meaning: "见识少的人遇到不常见的事物就觉得奇怪。" },
  { word: "舍己为人", pinyin: "shě jǐ wèi rén", first: "she", last: "ren", meaning: "舍弃自己的利益去帮助别人。" },
  { word: "舍本逐末", pinyin: "shě běn zhú mò", first: "she", last: "mo", meaning: "放弃根本的，追求末节的。" },
  { word: "深入浅出", pinyin: "shēn rù qiǎn chū", first: "shen", last: "chu", meaning: "用浅显易懂的话把深刻的道理表达出来。" },
  { word: "深思熟虑", pinyin: "shēn sī shú lǜ", first: "shen", last: "lv", meaning: "反复深入地考虑。" },
  { word: "生龙活虎", pinyin: "shēng lóng huó hǔ", first: "sheng", last: "hu", meaning: "形容活泼矫健，富有生气。" },
  { word: "生机勃勃", pinyin: "shēng jī bó bó", first: "sheng", last: "bo", meaning: "形容自然界充满生命力，或社会生活活跃。" },
  { word: "十拿九稳", pinyin: "shí ná jiǔ wěn", first: "shi", last: "wen", meaning: "比喻很有把握。" },
  { word: "十全十美", pinyin: "shí quán shí měi", first: "shi", last: "mei", meaning: "各方面都非常完美。" },
  { word: "实事求是", pinyin: "shí shì qiú shì", first: "shi", last: "shi", meaning: "从实际情况出发，不夸大，不缩小。" },
  { word: "事半功倍", pinyin: "shì bàn gōng bèi", first: "shi", last: "bei", meaning: "做事得法，因而费力小，收效大。" },
  { word: "势不两立", pinyin: "shì bù liǎng lì", first: "shi", last: "li", meaning: "指敌对的双方不能同时存在。" },
  { word: "守株待兔", pinyin: "shǒu zhū dài tù", first: "shou", last: "tu", meaning: "比喻不主动努力而存万一的侥幸心理。" },
  { word: "首屈一指", pinyin: "shǒu qū yī zhǐ", first: "shou", last: "zhi", meaning: "居第一位。" },
  { word: "手不释卷", pinyin: "shǒu bù shì juàn", first: "shou", last: "juan", meaning: "手不离书本，形容勤奋好学。" },
  { word: "手忙脚乱", pinyin: "shǒu máng jiǎo luàn", first: "shou", last: "luan", meaning: "形容做事慌张而没有条理。" },
  { word: "束手无策", pinyin: "shù shǒu wú cè", first: "shu", last: "ce", meaning: "就像手被捆住一样无法解脱。比喻一点办法也没有。" },
  { word: "水到渠成", pinyin: "shuǐ dào qú chéng", first: "shui", last: "cheng", meaning: "水流到的地方自然形成一条渠，比喻条件成熟事情就会自然成功。" },
  { word: "水落石出", pinyin: "shuǐ luò shí chū", first: "shui", last: "chu", meaning: "比喻事情的真相完全显露出来。" },
  { word: "水深火热", pinyin: "shuǐ shēn huǒ rè", first: "shui", last: "re", meaning: "比喻百姓生活极端困苦。" },
  { word: "顺手牵羊", pinyin: "shùn shǒu qiān yáng", first: "shun", last: "yang", meaning: "比喻趁便随手拿走别人的东西。" },
  { word: "说三道四", pinyin: "shuō sān dào sì", first: "shuo", last: "si", meaning: "不负责任地胡乱议论。" },
  { word: "四面楚歌", pinyin: "sì miàn chǔ gē", first: "si", last: "ge", meaning: "比喻陷入四面受敌，到达孤立无援的窘迫境地。" },
  { word: "四通八达", pinyin: "sì tōng bā dá", first: "si", last: "da", meaning: "四面八方都有路可通。形容交通方便。" },
  { word: "随机应变", pinyin: "suí jī yìng biàn", first: "sui", last: "bian", meaning: "随着情况的变化灵活机动地应付。" },
  { word: "损人利己", pinyin: "sǔn rén lì jǐ", first: "sun", last: "ji", meaning: "损害别人，使自己得到好处。" },

  // === T ===
  { word: "贪得无厌", pinyin: "tān dé wú yàn", first: "tan", last: "yan", meaning: "贪心永远没有满足的时候。" },
  { word: "叹为观止", pinyin: "tàn wéi guān zhǐ", first: "tan", last: "zhi", meaning: "赞美所见到的事物好到了极点。" },
  { word: "天经地义", pinyin: "tiān jīng dì yì", first: "tian", last: "yi", meaning: "理所当然的事情。" },
  { word: "天罗地网", pinyin: "tiān luó dì wǎng", first: "tian", last: "wang", meaning: "上下四方都布满了罗网。比喻对敌人或逃犯设下的包围圈。" },
  { word: "天马行空", pinyin: "tiān mǎ xíng kōng", first: "tian", last: "kong", meaning: "比喻思想奔放。" },
  { word: "天南地北", pinyin: "tiān nán dì běi", first: "tian", last: "bei", meaning: "形容地区各不相同，也比喻说话漫无边际。" },
  { word: "天涯海角", pinyin: "tiān yá hǎi jiǎo", first: "tian", last: "jiao", meaning: "形容极远的地方。" },
  { word: "天衣无缝", pinyin: "tiān yī wú fèng", first: "tian", last: "feng", meaning: "比喻事物周密完善，找不出什么毛病。" },
  { word: "铁杵成针", pinyin: "tiě chǔ chéng zhēn", first: "tie", last: "zhen", meaning: "比喻只要有毅力、肯下功夫，做任何事情都能成功。" },
  { word: "同甘共苦", pinyin: "tóng gān gòng kǔ", first: "tong", last: "ku", meaning: "一同享受幸福，一起分担艰苦。" },
  { word: "同心协力", pinyin: "tóng xīn xié lì", first: "tong", last: "li", meaning: "团结一致，共同努力。" },
  { word: "投机取巧", pinyin: "tóu jī qǔ qiǎo", first: "tou", last: "qiao", meaning: "利用时机和巧妙手段谋取利益。" },
  { word: "投其所好", pinyin: "tóu qí suǒ hào", first: "tou", last: "hao", meaning: "迎合别人的喜好。" },
  { word: "脱胎换骨", pinyin: "tuō tāi huàn gǔ", first: "tuo", last: "gu", meaning: "比喻彻底改变立场观点。" },

  // === W ===
  { word: "万马奔腾", pinyin: "wàn mǎ bēn téng", first: "wan", last: "teng", meaning: "形容声势浩大、气魄宏伟。" },
  { word: "万众一心", pinyin: "wàn zhòng yī xīn", first: "wan", last: "xin", meaning: "千千万万人一条心。形容团结一致。" },
  { word: "万紫千红", pinyin: "wàn zǐ qiān hóng", first: "wan", last: "hong", meaning: "形容百花齐放，色彩艳丽。" },
  { word: "亡羊补牢", pinyin: "wáng yáng bǔ láo", first: "wang", last: "lao", meaning: "羊逃跑了再去修补羊圈，还不算晚。比喻出了问题以后想办法补救。" },
  { word: "忘恩负义", pinyin: "wàng ēn fù yì", first: "wang", last: "yi", meaning: "忘记别人对自己的好处，反而做出对不起别人的事。" },
  { word: "望尘莫及", pinyin: "wàng chén mò jí", first: "wang", last: "ji", meaning: "只望见走在前面的人带起的尘土而追赶不上。比喻远远落后。" },
  { word: "望而生畏", pinyin: "wàng ér shēng wèi", first: "wang", last: "wei", meaning: "看见了就害怕。" },
  { word: "望梅止渴", pinyin: "wàng méi zhǐ kě", first: "wang", last: "ke", meaning: "比喻以空想安慰自己。" },
  { word: "微不足道", pinyin: "wēi bù zú dào", first: "wei", last: "dao", meaning: "微小得很，不值得一提。" },
  { word: "为虎作伥", pinyin: "wèi hǔ zuò chāng", first: "wei", last: "chang", meaning: "比喻给坏人当帮凶。" },
  { word: "围魏救赵", pinyin: "wéi wèi jiù zhào", first: "wei", last: "zhao", meaning: "指袭击敌人后方的据点以迫使进攻之敌撤退的战术。" },
  { word: "未雨绸缪", pinyin: "wèi yǔ chóu móu", first: "wei", last: "mou", meaning: "趁天没下雨先修好门窗。比喻事先做好准备工作。" },
  { word: "闻鸡起舞", pinyin: "wén jī qǐ wǔ", first: "wen", last: "wu", meaning: "听到鸡叫就起来舞剑。比喻有志报国的人及时奋起。" },
  { word: "文质彬彬", pinyin: "wén zhì bīn bīn", first: "wen", last: "bin", meaning: "形容人既文雅又朴实，后形容人文雅有礼貌。" },
  { word: "无地自容", pinyin: "wú dì zì róng", first: "wu", last: "rong", meaning: "没有地方可以让自己容身。形容非常惭愧。" },
  { word: "无动于衷", pinyin: "wú dòng yú zhōng", first: "wu", last: "zhong", meaning: "心里一点也没有触动。" },
  { word: "无可奈何", pinyin: "wú kě nài hé", first: "wu", last: "he", meaning: "没有办法，无法可想。" },
  { word: "无微不至", pinyin: "wú wēi bù zhì", first: "wu", last: "zhi", meaning: "形容关怀、照顾得非常细心周到。" },
  { word: "无忧无虑", pinyin: "wú yōu wú lǜ", first: "wu", last: "lv", meaning: "没有一点忧愁和顾虑。" },
  { word: "无中生有", pinyin: "wú zhōng shēng yǒu", first: "wu", last: "you", meaning: "把没有说成有。指凭空捏造。" },
  { word: "五湖四海", pinyin: "wǔ hú sì hǎi", first: "wu", last: "hai", meaning: "指全国各地。" },
  { word: "五光十色", pinyin: "wǔ guāng shí sè", first: "wu", last: "se", meaning: "形容色彩鲜艳，花样繁多。" },
  { word: "五体投地", pinyin: "wǔ tǐ tóu dì", first: "wu", last: "di", meaning: "比喻佩服到了极点。" },

  // === X ===
  { word: "喜出望外", pinyin: "xǐ chū wàng wài", first: "xi", last: "wai", meaning: "遇到出乎意料的喜事而特别高兴。" },
  { word: "先斩后奏", pinyin: "xiān zhǎn hòu zòu", first: "xian", last: "zou", meaning: "比喻先采取行动，然后再上报。" },
  { word: "相得益彰", pinyin: "xiāng dé yì zhāng", first: "xiang", last: "zhang", meaning: "互相配合、补充，更能显示各自的好处。" },
  { word: "相辅相成", pinyin: "xiāng fǔ xiāng chéng", first: "xiang", last: "cheng", meaning: "互相补充，互相配合。" },
  { word: "想入非非", pinyin: "xiǎng rù fēi fēi", first: "xiang", last: "fei", meaning: "思想进入虚幻境界，完全脱离实际。" },
  { word: "小题大做", pinyin: "xiǎo tí dà zuò", first: "xiao", last: "zuo", meaning: "把小事当做大事来办，形容把小事情看得太重。" },
  { word: "笑里藏刀", pinyin: "xiào lǐ cáng dāo", first: "xiao", last: "dao", meaning: "表面和善，背后使坏。" },
  { word: "心安理得", pinyin: "xīn ān lǐ dé", first: "xin", last: "de", meaning: "自以为做的事情合乎道理，心里很坦然。" },
  { word: "心旷神怡", pinyin: "xīn kuàng shén yí", first: "xin", last: "yi", meaning: "心境开阔，精神愉快。" },
  { word: "心血来潮", pinyin: "xīn xuè lái cháo", first: "xin", last: "chao", meaning: "比喻心中突然产生某种念头。" },
  { word: "心照不宣", pinyin: "xīn zhào bù xuān", first: "xin", last: "xuan", meaning: "彼此心里明白，而不公开说出来。" },
  { word: "兴高采烈", pinyin: "xìng gāo cǎi liè", first: "xing", last: "lie", meaning: "形容兴致高，精神饱满。" },
  { word: "兴风作浪", pinyin: "xīng fēng zuò làng", first: "xing", last: "lang", meaning: "比喻制造事端。" },
  { word: "胸有成竹", pinyin: "xiōng yǒu chéng zhú", first: "xiong", last: "zhu", meaning: "比喻做事之前已经有通盘的考虑和计划。" },
  { word: "虚张声势", pinyin: "xū zhāng shēng shì", first: "xu", last: "shi", meaning: "假装强大来吓唬别人。" },
  { word: "栩栩如生", pinyin: "xǔ xǔ rú shēng", first: "xu", last: "sheng", meaning: "形容画作、雕塑中的形象非常逼真。" },
  { word: "悬崖勒马", pinyin: "xuán yá lè mǎ", first: "xuan", last: "ma", meaning: "比喻到了危险的边缘及时清醒回头。" },
  { word: "学以致用", pinyin: "xué yǐ zhì yòng", first: "xue", last: "yong", meaning: "为了实际应用而学习。" },
  { word: "雪中送炭", pinyin: "xuě zhōng sòng tàn", first: "xue", last: "tan", meaning: "比喻在别人急需时给以物质上或精神上的帮助。" },

  // === Y ===
  { word: "鸦雀无声", pinyin: "yā què wú shēng", first: "ya", last: "sheng", meaning: "连乌鸦麻雀的声音都没有。形容非常静。" },
  { word: "掩耳盗铃", pinyin: "yǎn ěr dào líng", first: "yan", last: "ling", meaning: "比喻自己欺骗自己。" },
  { word: "眼花缭乱", pinyin: "yǎn huā liáo luàn", first: "yan", last: "luan", meaning: "眼睛看到复杂纷繁的东西而感到迷乱。" },
  { word: "叶落归根", pinyin: "yè luò guī gēn", first: "ye", last: "gen", meaning: "比喻事物总有一定的归宿。" },
  { word: "夜以继日", pinyin: "yè yǐ jì rì", first: "ye", last: "ri", meaning: "日夜不停。" },
  { word: "义不容辞", pinyin: "yì bù róng cí", first: "yi", last: "ci", meaning: "道义上不允许推辞。" },
  { word: "异口同声", pinyin: "yì kǒu tóng shēng", first: "yi", last: "sheng", meaning: "大家说的完全一致。" },
  { word: "异想天开", pinyin: "yì xiǎng tiān kāi", first: "yi", last: "kai", meaning: "比喻荒唐离奇，想象着暂时无法实现的事。" },
  { word: "引人注目", pinyin: "yǐn rén zhù mù", first: "yin", last: "mu", meaning: "吸引人们的注意。" },
  { word: "饮水思源", pinyin: "yǐn shuǐ sī yuán", first: "yin", last: "yuan", meaning: "喝水的时候想起水的来源。比喻不忘本。" },
  { word: "英雄豪杰", pinyin: "yīng xióng háo jié", first: "ying", last: "jie", meaning: "才能超群出众的人。" },
  { word: "应接不暇", pinyin: "yìng jiē bù xiá", first: "ying", last: "xia", meaning: "形容来人或事情太多，应付不过来。" },
  { word: "勇往直前", pinyin: "yǒng wǎng zhí qián", first: "yong", last: "qian", meaning: "勇敢地一直向前进。" },
  { word: "有恃无恐", pinyin: "yǒu shì wú kǒng", first: "you", last: "kong", meaning: "因为有所依仗而毫不害怕。" },
  { word: "有条不紊", pinyin: "yǒu tiáo bù wěn", first: "you", last: "wen", meaning: "形容有条有理，一点不乱。" },
  { word: "有目共睹", pinyin: "yǒu mù gòng dǔ", first: "you", last: "du", meaning: "人人都可以看到。" },
  { word: "与日俱增", pinyin: "yǔ rì jù zēng", first: "yu", last: "zeng", meaning: "随着时间一天天地增长。" },
  { word: "雨后春笋", pinyin: "yǔ hòu chūn sǔn", first: "yu", last: "sun", meaning: "比喻事物迅速大量地涌现出来。" },
  { word: "语重心长", pinyin: "yǔ zhòng xīn cháng", first: "yu", last: "chang", meaning: "话深刻有力，情意深长。" },
  { word: "缘木求鱼", pinyin: "yuán mù qiú yú", first: "yuan", last: "yu", meaning: "爬到树上去找鱼，比喻方向或办法不对，不可能达到目的。" },
  { word: "远走高飞", pinyin: "yuǎn zǒu gāo fēi", first: "yuan", last: "fei", meaning: "向远处走、向高处飞。比喻逃离。" },

  // === Z ===
  { word: "斩草除根", pinyin: "zhǎn cǎo chú gēn", first: "zhan", last: "gen", meaning: "比喻除去祸根，不留后患。" },
  { word: "张灯结彩", pinyin: "zhāng dēng jié cǎi", first: "zhang", last: "cai", meaning: "挂上灯笼，系上彩绸。形容节日或有喜庆的景象。" },
  { word: "朝三暮四", pinyin: "zhāo sān mù sì", first: "zhao", last: "si", meaning: "比喻常常变卦，反复无常。" },
  { word: "招兵买马", pinyin: "zhāo bīng mǎi mǎ", first: "zhao", last: "ma", meaning: "比喻组织或扩充人力。" },
  { word: "纸上谈兵", pinyin: "zhǐ shàng tán bīng", first: "zhi", last: "bing", meaning: "在纸面上谈论打仗，比喻空谈理论，不能解决实际问题。" },
  { word: "指鹿为马", pinyin: "zhǐ lù wéi mǎ", first: "zhi", last: "ma", meaning: "比喻故意颠倒黑白，混淆是非。" },
  { word: "志同道合", pinyin: "zhì tóng dào hé", first: "zhi", last: "he", meaning: "志向相同，道路一致。" },
  { word: "众志成城", pinyin: "zhòng zhì chéng chéng", first: "zhong", last: "cheng", meaning: "万众一心，像坚固的城堡一样不可摧毁。" },
  { word: "众矢之的", pinyin: "zhòng shǐ zhī dì", first: "zhong", last: "di", meaning: "许多箭射击的目标。比喻大家攻击的对象。" },
  { word: "珠联璧合", pinyin: "zhū lián bì hé", first: "zhu", last: "he", meaning: "比喻杰出的人才或美好的事物结合在一起。" },
  { word: "自力更生", pinyin: "zì lì gēng shēng", first: "zi", last: "sheng", meaning: "依靠自己的力量改变原来的情况而发展起来。" },
  { word: "自以为是", pinyin: "zì yǐ wéi shì", first: "zi", last: "shi", meaning: "总以为自己是对的，形容主观不虚心。" },
  { word: "自相矛盾", pinyin: "zì xiāng máo dùn", first: "zi", last: "dun", meaning: "比喻自己说话做事前后抵触。" },
  { word: "自暴自弃", pinyin: "zì bào zì qì", first: "zi", last: "qi", meaning: "自己甘心落后，不求上进。" },
  { word: "左右逢源", pinyin: "zuǒ yòu féng yuán", first: "zuo", last: "yuan", meaning: "比喻做事得心应手。" },
  { word: "坐井观天", pinyin: "zuò jǐng guān tiān", first: "zuo", last: "tian", meaning: "坐在井里看天，比喻见识狭小。" },
  { word: "坐立不安", pinyin: "zuò lì bù ān", first: "zuo", last: "an", meaning: "坐着也不是，站着也不是。形容心情紧张，情绪不安。" },
  { word: "走马观花", pinyin: "zǒu mǎ guān huā", first: "zou", last: "hua", meaning: "比喻粗略地观察事物。" },
  { word: "作茧自缚", pinyin: "zuò jiǎn zì fù", first: "zuo", last: "fu", meaning: "比喻做了某事，结果反而使自己受困。" },

  // === 更多补充 ===
  { word: "安身立命", pinyin: "ān shēn lì mìng", first: "an", last: "ming", meaning: "生活有着落，精神有所寄托。" },
  { word: "傲雪凌霜", pinyin: "ào xuě líng shuāng", first: "ao", last: "shuang", meaning: "形容不畏严寒，也比喻人不怕挫折。" },
  { word: "百战百胜", pinyin: "bǎi zhàn bǎi shèng", first: "bai", last: "sheng", meaning: "每战必胜，形容所向无敌。" },
  { word: "百里挑一", pinyin: "bǎi lǐ tiāo yī", first: "bai", last: "yi", meaning: "一百个当中选出一个。形容十分出众。" },
  { word: "百感交集", pinyin: "bǎi gǎn jiāo jí", first: "bai", last: "ji", meaning: "各种感触交织在一起。形容感触很多、很复杂。" },
  { word: "饱经沧桑", pinyin: "bǎo jīng cāng sāng", first: "bao", last: "sang", meaning: "形容经历过很多世事变迁。" },
  { word: "暴殄天物", pinyin: "bào tiǎn tiān wù", first: "bao", last: "wu", meaning: "任意糟蹋东西。" },
  { word: "抱残守缺", pinyin: "bào cán shǒu quē", first: "bao", last: "que", meaning: "抱着残缺的东西不放。形容思想保守、不求改进。" },
  { word: "筚路蓝缕", pinyin: "bì lù lán lǚ", first: "bi", last: "lv", meaning: "形容创业的艰苦。" },
  { word: "鞭长莫及", pinyin: "biān cháng mò jí", first: "bian", last: "ji", meaning: "比喻力量达不到。" },
  { word: "彬彬有礼", pinyin: "bīn bīn yǒu lǐ", first: "bin", last: "li", meaning: "形容文雅有礼貌的样子。" },
  { word: "波澜壮阔", pinyin: "bō lán zhuàng kuò", first: "bo", last: "kuo", meaning: "比喻声势雄壮或规模巨大。" },
  { word: "不遗余力", pinyin: "bù yí yú lì", first: "bu", last: "li", meaning: "把全部力量都使出来，一点不保留。" },
  { word: "不翼而飞", pinyin: "bù yì ér fēi", first: "bu", last: "fei", meaning: "没有翅膀却飞走了。比喻东西突然不见了。" },
  { word: "不辞劳苦", pinyin: "bù cí láo kǔ", first: "bu", last: "ku", meaning: "不怕辛劳和困苦。" },
  { word: "不落窠臼", pinyin: "bù luò kē jiù", first: "bu", last: "jiu", meaning: "不落俗套。" },
  { word: "不胫而走", pinyin: "bù jìng ér zǒu", first: "bu", last: "zou", meaning: "比喻事物无需推行就已迅速地传播开了。" },
  { word: "才华横溢", pinyin: "cái huá héng yì", first: "cai", last: "yi", meaning: "形容才能非常出众。" },
  { word: "残花败柳", pinyin: "cán huā bài liǔ", first: "can", last: "liu", meaning: "凋残的花和枯败的柳。" },
  { word: "苍翠欲滴", pinyin: "cāng cuì yù dī", first: "cang", last: "di", meaning: "形容草木等绿色植物长得苍翠茂盛。" },
  { word: "草长莺飞", pinyin: "cǎo zhǎng yīng fēi", first: "cao", last: "fei", meaning: "形容江南暮春的景色。" },
  { word: "层出不穷", pinyin: "céng chū bù qióng", first: "ceng", last: "qiong", meaning: "接连不断地出现，没有穷尽。" },
  { word: "朝气蓬勃", pinyin: "zhāo qì péng bó", first: "zhao", last: "bo", meaning: "形容充满了生命和活力。" },
  { word: "大刀阔斧", pinyin: "dà dāo kuò fǔ", first: "da", last: "fu", meaning: "比喻办事果断而有魄力。" },
  { word: "大名鼎鼎", pinyin: "dà míng dǐng dǐng", first: "da", last: "ding", meaning: "形容名气很大。" },
  { word: "大相径庭", pinyin: "dà xiāng jìng tíng", first: "da", last: "ting", meaning: "比喻相差很远，大不相同。" },
  { word: "胆大妄为", pinyin: "dǎn dà wàng wéi", first: "dan", last: "wei", meaning: "毫无顾忌地做坏事。" },
  { word: "胆战心惊", pinyin: "dǎn zhàn xīn jīng", first: "dan", last: "jing", meaning: "形容非常害怕。" },
  { word: "刀光剑影", pinyin: "dāo guāng jiàn yǐng", first: "dao", last: "ying", meaning: "形容充满了刀剑的闪光和影子。形容环境充满了凶险的气氛。" },
  { word: "倒行逆施", pinyin: "dào xíng nì shī", first: "dao", last: "shi", meaning: "原指做事违反常理，不择手段。" },
  { word: "登峰造极", pinyin: "dēng fēng zào jí", first: "deng", last: "ji", meaning: "比喻学问、技能等达到最高的境界。" },
  { word: "点石成金", pinyin: "diǎn shí chéng jīn", first: "dian", last: "jin", meaning: "比喻把不好的或平凡的事物改变成好的事物。" },
  { word: "跌宕起伏", pinyin: "diē dàng qǐ fú", first: "die", last: "fu", meaning: "形容事物多变，不稳定。" },
  { word: "独占鳌头", pinyin: "dú zhàn áo tóu", first: "du", last: "tou", meaning: "比喻居首位或第一名。" },
  { word: "堆积如山", pinyin: "duī jī rú shān", first: "dui", last: "shan", meaning: "聚集成堆，如同小山。形容极多。" },
  { word: "恩重如山", pinyin: "ēn zhòng rú shān", first: "en", last: "shan", meaning: "恩情像山一样深重。" },
  { word: "翻来覆去", pinyin: "fān lái fù qù", first: "fan", last: "qu", meaning: "形容一次又一次。也形容来回翻动身体。" },
  { word: "繁花似锦", pinyin: "fán huā sì jǐn", first: "fan", last: "jin", meaning: "许多色彩纷繁的鲜花，好像富丽多彩的锦缎。" },
  { word: "返璞归真", pinyin: "fǎn pú guī zhēn", first: "fan", last: "zhen", meaning: "去掉外饰，还其本质。" },
  { word: "放虎归山", pinyin: "fàng hǔ guī shān", first: "fang", last: "shan", meaning: "比喻放走敌人，自留后患。" },
  { word: "肝胆相照", pinyin: "gān dǎn xiāng zhào", first: "gan", last: "zhao", meaning: "比喻以真心诚意相待。" },
  { word: "甘之如饴", pinyin: "gān zhī rú yí", first: "gan", last: "yi", meaning: "感到像糖一样甜。比喻甘愿承受艰苦。" },
  { word: "感同身受", pinyin: "gǎn tóng shēn shòu", first: "gan", last: "shou", meaning: "虽然没有亲身经历，但感受就像亲身经历过一样。" },
  { word: "隔岸观火", pinyin: "gé àn guān huǒ", first: "ge", last: "huo", meaning: "比喻对别人的危难不去救助。" },
  { word: "瓜田李下", pinyin: "guā tián lǐ xià", first: "gua", last: "xia", meaning: "比喻容易引起嫌疑的场合。" },
  { word: "光阴似箭", pinyin: "guāng yīn sì jiàn", first: "guang", last: "jian", meaning: "时间像箭一样飞快地过去。" },
  { word: "归心似箭", pinyin: "guī xīn sì jiàn", first: "gui", last: "jian", meaning: "想回家的心情像射出的箭一样快。形容回家心切。" },
  { word: "海市蜃楼", pinyin: "hǎi shì shèn lóu", first: "hai", last: "lou", meaning: "比喻虚幻的事物。" },
  { word: "害群之马", pinyin: "hài qún zhī mǎ", first: "hai", last: "ma", meaning: "比喻危害群众利益的人。" },
  { word: "毫不犹豫", pinyin: "háo bù yóu yù", first: "hao", last: "yu", meaning: "一点也不迟疑。" },
  { word: "好逸恶劳", pinyin: "hào yì wù láo", first: "hao", last: "lao", meaning: "贪图安逸，厌恶劳动。" },
  { word: "和蔼可亲", pinyin: "hé ǎi kě qīn", first: "he", last: "qin", meaning: "态度温和，容易接近。" },
  { word: "虎视眈眈", pinyin: "hǔ shì dān dān", first: "hu", last: "dan", meaning: "像老虎那样凶狠地盯着。形容心怀不善，伺机掠取。" },
  { word: "患得患失", pinyin: "huàn dé huàn shī", first: "huan", last: "shi", meaning: "担心得不到，得到了又担心失去。形容对个人得失看得很重。" },
  { word: "积少成多", pinyin: "jī shǎo chéng duō", first: "ji", last: "duo", meaning: "积累少的成为多的。" },
  { word: "记忆犹新", pinyin: "jì yì yóu xīn", first: "ji", last: "xin", meaning: "过去的事，至今印象还非常清楚。" },
  { word: "家喻户晓", pinyin: "jiā yù hù xiǎo", first: "jia", last: "xiao", meaning: "每家每户都知道。" },
  { word: "价值连城", pinyin: "jià zhí lián chéng", first: "jia", last: "cheng", meaning: "形容物品十分贵重。" },
  { word: "坚不可摧", pinyin: "jiān bù kě cuī", first: "jian", last: "cui", meaning: "非常坚固，摧毁不了。" },
  { word: "兼听则明", pinyin: "jiān tīng zé míng", first: "jian", last: "ming", meaning: "听取多方面的意见就能明辨是非。" },
  { word: "江山如画", pinyin: "jiāng shān rú huà", first: "jiang", last: "hua", meaning: "山川风景像画一样美丽。" },
  { word: "将计就计", pinyin: "jiāng jì jiù jì", first: "jiang", last: "ji", meaning: "利用对方所用的计策反过来对付对方。" },
  { word: "脚踏实地", pinyin: "jiǎo tà shí dì", first: "jiao", last: "di", meaning: "比喻做事认真踏实。" },
  { word: "竭尽全力", pinyin: "jié jìn quán lì", first: "jie", last: "li", meaning: "用尽全部力量。" },
  { word: "金碧辉煌", pinyin: "jīn bì huī huáng", first: "jin", last: "huang", meaning: "形容建筑物装饰华丽，光彩夺目。" },
  { word: "金榜题名", pinyin: "jīn bǎng tí míng", first: "jin", last: "ming", meaning: "比喻考试被录取。" },
  { word: "金玉良言", pinyin: "jīn yù liáng yán", first: "jin", last: "yan", meaning: "比喻非常宝贵的劝告或教诲。" },
  { word: "津津有味", pinyin: "jīn jīn yǒu wèi", first: "jin", last: "wei", meaning: "形容兴趣浓厚或有滋味。" },
  { word: "进退两难", pinyin: "jìn tuì liǎng nán", first: "jin", last: "nan", meaning: "前进和后退都有困难。形容陷于困境。" },
  { word: "惊涛骇浪", pinyin: "jīng tāo hài làng", first: "jing", last: "lang", meaning: "比喻险恶的环境或尖锐激烈的斗争。" },
  { word: "精诚团结", pinyin: "jīng chéng tuán jié", first: "jing", last: "jie", meaning: "真诚地团结在一起。" },
  { word: "举目无亲", pinyin: "jǔ mù wú qīn", first: "ju", last: "qin", meaning: "抬起眼睛，看不见一个亲人。形容单身在外，人地生疏。" },
  { word: "卷土重来", pinyin: "juǎn tǔ chóng lái", first: "juan", last: "lai", meaning: "比喻失败之后重新恢复势力。" },
  { word: "决一死战", pinyin: "jué yī sǐ zhàn", first: "jue", last: "zhan", meaning: "对敌人拼死决战。" },
  { word: "绝处逢生", pinyin: "jué chù féng shēng", first: "jue", last: "sheng", meaning: "在走投无路的情况下找到了出路。" },
  { word: "可歌可泣", pinyin: "kě gē kě qì", first: "ke", last: "qi", meaning: "值得歌颂赞美，使人感动流泪。" },
  { word: "空前绝后", pinyin: "kōng qián jué hòu", first: "kong", last: "hou", meaning: "以前没有过，以后也不会有。形容超绝古今。" },
  { word: "口碑载道", pinyin: "kǒu bēi zài dào", first: "kou", last: "dao", meaning: "形容到处受到称赞。" },
  { word: "夸父追日", pinyin: "kuā fù zhuī rì", first: "kua", last: "ri", meaning: "比喻有宏大的志向或巨大的力量和气魄。" },
  { word: "狼吞虎咽", pinyin: "láng tūn hǔ yàn", first: "lang", last: "yan", meaning: "形容吃东西又猛又急的样子。" },
  { word: "劳苦功高", pinyin: "láo kǔ gōng gāo", first: "lao", last: "gao", meaning: "做事勤苦，功劳很大。" },
  { word: "雷厉风行", pinyin: "léi lì fēng xíng", first: "lei", last: "xing", meaning: "比喻执行政策法令严厉迅速。" },
  { word: "冷嘲热讽", pinyin: "lěng cháo rè fěng", first: "leng", last: "feng", meaning: "用尖刻辛辣的语言进行嘲笑和讽刺。" },
  { word: "粒粒皆辛苦", pinyin: "lì lì jiē xīn kǔ", first: "li", last: "ku", meaning: "每一粒粮食都是辛苦劳动得来的。" },
  { word: "量力而行", pinyin: "liàng lì ér xíng", first: "liang", last: "xing", meaning: "按照自己力量的大小去做。" },
  { word: "琳琅满目", pinyin: "lín láng mǎn mù", first: "lin", last: "mu", meaning: "满眼都是珍贵的东西，形容美好的事物很多。" },
  { word: "龙马精神", pinyin: "lóng mǎ jīng shén", first: "long", last: "shen", meaning: "比喻人精神旺盛。" },
  { word: "柳暗花明", pinyin: "liǔ àn huā míng", first: "liu", last: "ming", meaning: "比喻在困难中遇到转机。" },
  { word: "鸣锣开道", pinyin: "míng luó kāi dào", first: "ming", last: "dao", meaning: "比喻为某件事情的开始做舆论宣传。" },
  { word: "摩肩接踵", pinyin: "mó jiān jiē zhǒng", first: "mo", last: "zhong", meaning: "肩碰肩，脚碰脚。形容来往行人很多，很拥挤。" },
  { word: "目不转睛", pinyin: "mù bù zhuǎn jīng", first: "mu", last: "jing", meaning: "眼珠一动不动地盯着看。形容注意力集中。" },
  { word: "怒发冲冠", pinyin: "nù fà chōng guān", first: "nu", last: "guan", meaning: "形容极端愤怒。" },
  { word: "旁征博引", pinyin: "páng zhēng bó yǐn", first: "pang", last: "yin", meaning: "广泛地引用材料作为证据。" },
  { word: "鹏程万里", pinyin: "péng chéng wàn lǐ", first: "peng", last: "li", meaning: "比喻前程远大。" },
  { word: "劈波斩浪", pinyin: "pī bō zhǎn làng", first: "pi", last: "lang", meaning: "比喻排除阻碍，奋勇前进。" },
  { word: "气壮山河", pinyin: "qì zhuàng shān hé", first: "qi", last: "he", meaning: "形容气概豪迈，使祖国山河因而更加壮丽。" },
  { word: "千军万马", pinyin: "qiān jūn wàn mǎ", first: "qian", last: "ma", meaning: "形容雄壮的队伍或浩大的声势。" },
  { word: "千姿百态", pinyin: "qiān zī bǎi tài", first: "qian", last: "tai", meaning: "形容姿态多种多样。" },
  { word: "窃窃私语", pinyin: "qiè qiè sī yǔ", first: "qie", last: "yu", meaning: "暗地里小声说话。" },
  { word: "倾盆大雨", pinyin: "qīng pén dà yǔ", first: "qing", last: "yu", meaning: "雨大得像盆里的水直往下倒。形容雨大势急。" },
  { word: "人声鼎沸", pinyin: "rén shēng dǐng fèi", first: "ren", last: "fei", meaning: "形容人群的声音嘈杂喧闹。" },
  { word: "忍辱负重", pinyin: "rěn rǔ fù zhòng", first: "ren", last: "zhong", meaning: "为了完成艰巨的任务，忍受暂时的屈辱。" },
  { word: "三顾茅庐", pinyin: "sān gù máo lú", first: "san", last: "lu", meaning: "比喻真心诚意一再邀请。" },
  { word: "势如破竹", pinyin: "shì rú pò zhú", first: "shi", last: "zhu", meaning: "比喻节节胜利，毫无阻碍。" },
  { word: "谈笑风生", pinyin: "tán xiào fēng shēng", first: "tan", last: "sheng", meaning: "形容谈话时说说笑笑，有说有笑，兴致很高。" },
  { word: "桃李满天下", pinyin: "táo lǐ mǎn tiān xià", first: "tao", last: "xia", meaning: "比喻学生很多，各地都有。" },
  { word: "醍醐灌顶", pinyin: "tí hú guàn dǐng", first: "ti", last: "ding", meaning: "比喻听了高明的意见使人受到很大启发。" },
  { word: "痛改前非", pinyin: "tòng gǎi qián fēi", first: "tong", last: "fei", meaning: "彻底改正以前所犯的错误。" },
  { word: "万古流芳", pinyin: "wàn gǔ liú fāng", first: "wan", last: "fang", meaning: "好名声永远流传。" },
  { word: "万水千山", pinyin: "wàn shuǐ qiān shān", first: "wan", last: "shan", meaning: "形容路途艰难遥远。" },
  { word: "唯利是图", pinyin: "wéi lì shì tú", first: "wei", last: "tu", meaning: "只贪图利益，不顾其他。" },
  { word: "问心无愧", pinyin: "wèn xīn wú kuì", first: "wen", last: "kui", meaning: "扪心自问，毫无愧色。形容没有做亏心事。" },
  { word: "卧薪尝胆", pinyin: "wò xīn cháng dǎn", first: "wo", last: "dan", meaning: "比喻刻苦自励，发奋图强。" },
  { word: "喜气洋洋", pinyin: "xǐ qì yáng yáng", first: "xi", last: "yang", meaning: "充满了欢喜的神色或气氛。" },
  { word: "心驰神往", pinyin: "xīn chí shén wǎng", first: "xin", last: "wang", meaning: "心神奔向所向往的事物。形容一心向往。" },
  { word: "心花怒放", pinyin: "xīn huā nù fàng", first: "xin", last: "fang", meaning: "心里高兴得像花儿盛开一样。形容极其高兴。" },
  { word: "心灰意冷", pinyin: "xīn huī yì lěng", first: "xin", last: "leng", meaning: "灰心丧气，意志消沉。" },
  { word: "星罗棋布", pinyin: "xīng luó qí bù", first: "xing", last: "bu", meaning: "像星星似的罗列着，像棋子似的分布着。形容数量很多、分布很广。" },
  { word: "雄心壮志", pinyin: "xióng xīn zhuàng zhì", first: "xiong", last: "zhi", meaning: "伟大的理想，宏伟的志愿。" },
  { word: "言简意赅", pinyin: "yán jiǎn yì gāi", first: "yan", last: "gai", meaning: "言语简练而意思完备。" },
  { word: "扬长避短", pinyin: "yáng cháng bì duǎn", first: "yang", last: "duan", meaning: "发挥长处，避开短处。" },
  { word: "一视同仁", pinyin: "yī shì tóng rén", first: "yi", last: "ren", meaning: "不分厚薄，同样看待。" },
  { word: "意气风发", pinyin: "yì qì fēng fā", first: "yi", last: "fa", meaning: "形容精神振奋，气概豪迈。" },
  { word: "因地制宜", pinyin: "yīn dì zhì yí", first: "yin", last: "yi", meaning: "根据各地的具体情况制定适宜的办法。" },
  { word: "迎刃而解", pinyin: "yíng rèn ér jiě", first: "ying", last: "jie", meaning: "比喻主要问题解决了，其他的问题就很容易解决。" },
  { word: "油然而生", pinyin: "yóu rán ér shēng", first: "you", last: "sheng", meaning: "自然地产生某种思想感情。" },
  { word: "有声有色", pinyin: "yǒu shēng yǒu sè", first: "you", last: "se", meaning: "形容表现得生动形象。" },
  { word: "与世隔绝", pinyin: "yǔ shì gé jué", first: "yu", last: "jue", meaning: "与社会上的人们隔离，断绝来往。" },
  { word: "愚公移山", pinyin: "yú gōng yí shān", first: "yu", last: "shan", meaning: "比喻坚持不懈地改造自然和坚定不移地进行斗争。" },
  { word: "源远流长", pinyin: "yuán yuǎn liú cháng", first: "yuan", last: "chang", meaning: "比喻历史悠久。" },
  { word: "运筹帷幄", pinyin: "yùn chóu wéi wò", first: "yun", last: "wo", meaning: "在后方决定作战策略。" },
  { word: "再接再厉", pinyin: "zài jiē zài lì", first: "zai", last: "li", meaning: "一次又一次地继续努力。" },
  { word: "争先恐后", pinyin: "zhēng xiān kǒng hòu", first: "zheng", last: "hou", meaning: "争着向前，唯恐落后。" },
  { word: "知己知彼", pinyin: "zhī jǐ zhī bǐ", first: "zhi", last: "bi", meaning: "了解自己，了解对手。" },
  { word: "中流砥柱", pinyin: "zhōng liú dǐ zhù", first: "zhong", last: "zhu", meaning: "比喻坚强独立的人能在动荡艰难中起支柱作用。" },
  { word: "专心致志", pinyin: "zhuān xīn zhì zhì", first: "zhuan", last: "zhi", meaning: "一心一意，集中精神。" },
  { word: "壮志凌云", pinyin: "zhuàng zhì líng yún", first: "zhuang", last: "yun", meaning: "形容理想宏伟远大。" },
  { word: "自告奋勇", pinyin: "zì gào fèn yǒng", first: "zi", last: "yong", meaning: "主动要求担任某项艰巨的任务。" },
  { word: "自强不息", pinyin: "zì qiáng bù xī", first: "zi", last: "xi", meaning: "自己努力向上，永远不懈怠。" },
  { word: "纵横驰骋", pinyin: "zòng héng chí chěng", first: "zong", last: "cheng", meaning: "形容作战英勇，所向无敌。" },
  { word: "足智多谋", pinyin: "zú zhì duō móu", first: "zu", last: "mou", meaning: "富有智慧和善于谋划。" },
];

// 合并并去重
const merged = [...existing];
const seen = new Set(existingWords);

for (const item of newIdioms) {
  if (!seen.has(item.word)) {
    seen.add(item.word);
    merged.push(item);
  }
}

// 验证数据完整性
let errors = 0;
for (const item of merged) {
  if (!item.word || !item.pinyin || !item.first || !item.last || !item.meaning) {
    console.error(`数据不完整: ${item.word}`);
    errors++;
  }
}

fs.writeFileSync(existingPath, JSON.stringify(merged, null, 2), 'utf-8');
console.log(`合并完成: 原 ${existing.length} 条 + 新 ${merged.length - existing.length} 条 = 共 ${merged.length} 条`);
console.log(`错误: ${errors} 条`);
